cluster.name: "docker-cluster"
xpack.security.authc.realms.oidc.oidc1:
  order: 1
  rp.client_id: "the_client_id"
  rp.response_type: code
  rp.redirect_uri: "https://localhost:5601/api/security/oidc/callback"
  op.issuer: "http://server.local"
  op.authorization_endpoint: "http://server.local/login"
  op.token_endpoint: "https://op.example.org/oauth2/v1/token"
  op.jwkset_path: "https://www.googleapis.com/oauth2/v3/certs"
  op.userinfo_endpoint: "https://op.example.org/oauth2/v1/userinfo"
  op.endsession_endpoint: "https://op.example.org/oauth2/v1/logout"
  rp.post_logout_redirect_uri: "https://localhost:5601/logged_out"
  claims.principal: sub
  claims.groups: "http://example.info/claims/groups"

xpack.security.authc.token.enabled: true

node.name: node1
network.host: elasticsearch
xpack.security.enabled: true
xpack.security.http.ssl.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certs/node1/node1.key
xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certs/node1/node1.crt
xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca/ca.crt
xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certs/node1/node1.key
xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certs/node1/node1.crt
xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca/ca.crt
discovery.seed_hosts: [ "elasticsearch" ]
cluster.initial_master_nodes: [ "node1" ]
